### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by scorpieli** [web-fonts/web-fonts#11]
გამარჯობა, 
თუ შეიძლება დამეხმაროთ ვერაფრით ვერ გავმართე ქართული ფონტი საიტზე.
ვირტუალური ჰოსტინგია proservice.ge-ზე. 

HTML ში- ჩავამატე შემდეგი კოდი`<link rel="stylesheet" href="//cdn.web-fonts.ge/fonts/dejavu-sans/css/dejavu-sans.min.css">`

CSS-შიც დავამატე კონკრედული მოდულში
`font-family: "DejaVu Sans", sans-serif;`

მაგრამ შედეგი არ მომცა მაინც იეროგლიფებით მიჩვენებს

> ÁƑ©ÁƑ•ÁƑ”ÁƑŒÁƑ¡ ÁƑ¨ÁƑ”ÁƑ¡ÁƑÁƑ®ÁƑ”ÁƑ‘

გთხოვთ დამაკვალიანოთ

**Comment by liorocks** [comment]
პრობლემა კოდირებაშია და არა ფონტში.

HTML ტეგს დაუმატეთ UTF-8 კოდირების მიმთითებელი meta ტეგი:

```html
<meta charset="utf-8">
```


Demo: http://output.jsbin.com/vezonofoxi
