### ISSUE TITLE
ფონტი BPG Glaho

### ISSUE THREAD

**Issue by giorgi-gagloshvili** [web-fonts/web-fonts#12]
გამარჯობა როგორც საიტზე ეწერა ინსტრუქცია შევიტანე ფონტი html-ში და ბრაუზერმა დაარენდერა, მაგრამ მინდა დიდი ასოებით დაწერა (ერთი ზომის მწკრივში ჩაწერილი შრიფტი) და ვერ ვხვდები როგორ უნდა გავაკეთო, text-transform: uppercase დავუწურე css-ში მაგრამ არ იმუშავა

მადლობა წინასწარ

**Comment by liorocks** [comment]
@giorgaa 

```
text-transform: uppercase
```
სამწუხაროდ, ეს პარამეტრი ქართულ ფონტებზე/სიმბოლოებზე არ მუშაობს.

ამ ეტაპზე საიტზე არსებულ არცერთ ფონტს არ გააჩნია მთავრულის და ნუსხურის _ერთდროული_ მხარდაჭერა. 

ამ დროისთვის მხოლოდ [BPG Glaho WEB Caps](https://web-fonts.ge/bpg-glaho-web-caps/)-ს აქვს _ამ ფონტის ოჯახიდან  (BPG Glaho)_ მთავრული სიმბოლოების მხარდაჭერის საშუალება.

**Comment by giorgi-gagloshvili** [comment]
მადლობა მეგობარო

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-22 0:05 GMT+04:00 Lado Lomidze <notifications@github.com>:
