### ISSUE TITLE
BPG Phone Sans (Bold too)

### ISSUE THREAD

**Issue by Lotuashvili** [web-fonts/web-fonts#9]
http://fonts.ge/ka/font/489/BPG-Phone-Sans
http://fonts.ge/ka/font/490/BPG-Phone-Sans-Bold

**Comment by liorocks** [comment]
https://github.com/web-fonts/bpg-phone-sans
https://github.com/web-fonts/bpg-phone-sans-bold
https://github.com/web-fonts/bpg-phone-sans-italic
https://github.com/web-fonts/bpg-phone-sans-bold-italic
